### ISSUE TITLE
Script.sh Start is Broken

### ISSUE THREAD

**Issue by joesixpack** [ElrondNetwork/elrond-go-scripts-v2#10]
Start worked once, now it doesn't launch the nodes anymore.  They work fine when launched manually.

It's also really, really, really bad practice to be requiring the nodes to be run as root.  If you install them as root via the script, the directory permissions will prevent access as non-root thereafter.

**Comment by koen84** [comment]
It's not required to run the nodes as root !!  I'm not.  Alwin is not.  Possibly others are neither...

Obviously, if you want to run as non-root, you shouldn't run the script as root but as your intended user.    Either way, merged #8 should fix this regardless.

**Comment by joesixpack** [comment]
The directions specifically said to run the script as root... though I ran it both ways when installing and not sure I noticed a difference, other than that maybe they won't start anymore after doing it the root way.

Anyway since I can't get this working, I'm going to clean up and fix the autoupdate.sh script and use it with my existing launch system which I have much more robust confidence in.

**Comment by valentin-lup** [comment]
koen84 is absolutely right. You do not need root to run the scripts. But the user you run the nodes under must be sudo capable (without password) in order to start/stop nodes which run as systemd units.
