### ISSUE TITLE
Why not just use ansible

### ISSUE THREAD

**Issue by liuyangc3** [ElrondNetwork/elrond-go-scripts-v2#12]
I saw the script use ssh key to update project

**Comment by koen84** [comment]
My guess is lower entry barrier.  And wouldn't ansible require ssh (key) too ?

**Comment by liuyangc3** [comment]
Yeah ansible depends on SSH, password or key is both support

**Comment by valentin-lup** [comment]
It uses an ssh key if you wish to remote install nodes... yes...
