### ISSUE TITLE
Number of Nodes and connection refused for only one node while others are running

### ISSUE THREAD

**Issue by victoroshi** [ElrondNetwork/elrond-go-scripts-v2#16]
1. When installing the node, the stage where the number of nodes desired to run is required, if non-numeric is entered (such as @, <, ~, g p, { ), it will proceed and cause error almost at the tail end. There should be a proper way to check the input provided at this stage and prompt for error

2. As shown below, connection refused for only one node while others are running. It will be good if there seems to be a way to check that the extension is **.pem** and no other **.** in the form of extension after this. I faced this issue with .0000 attached to the end of my pem keys (like this initialBalancesSk.pem.0000000 ), how this occurred still remain weird
![image](https://user-images.githubusercontent.com/7301249/70051795-1fdb4280-15d2-11ea-8b7f-db61cbb9fac5.png)

**Comment by koen84** [comment]
Should be fixed with #2
