### ISSUE TITLE
Auto-updater pulls new version successfully but fails to copy the new binary to nodes' folders

### ISSUE THREAD

**Issue by anhnd** [ElrondNetwork/elrond-go-scripts-v2#20]
So Auto-updater pulls new version successfully but fails to copy the new binary to nodes' folders for some reasons. In this case Auto-updater won't work anymore. Maybe the script should not check current version from local repo, instead maybe it can check current version from nodes' binaries.

**Comment by koen84** [comment]
Possibly addressed by PR #19

**Comment by anhnd** [comment]
Closed because it is duplicated with #1
