### ISSUE TITLE
Auto-updater on a multiple nodes machine might not work correctly

### ISSUE THREAD

**Issue by anhnd** [ElrondNetwork/elrond-go-scripts-v2#32]
I think with "CURRENT=$(curl -s http://localhost:8080/node/status | jq -r .details.erd_app_version)", if we run multiple nodes there is still a chance that some nodes won't update right(because the first node updated successfully but the second one failed ...)? Maybe the script can store the version number somewhere after all nodes are updated successfully or use numberofnodes to check if all the nodes are updated ?

**Comment by valentin-lup** [comment]
Yes ! That's exactly what I was thinking. Working on it as we speak !

**Comment by valentin-lup** [comment]
This has been fixed by a recent PR. Closing
