### ISSUE TITLE
Node monitor color in termui

### ISSUE THREAD

**Issue by Mystic999** [ElrondNetwork/elrond-go-scripts-v2#34]
Noticed a strange feature of the new scripts. When using terminal Git Bash for Windows. Strange color scheme of the monitor window. The node runs remotely on a VPS with Root privileges
![ScreenGif](https://user-images.githubusercontent.com/52602853/70212042-9fd6e900-1747-11ea-9f6e-25a6535d9140.gif)

**Comment by valentin-lup** [comment]
I'll have the guys look into it !

**Comment by bogdan-rosianu** [comment]
Hello ! Have you tried with Windows's command prompt or something else ? The issue may be related to git bash

**Comment by valentin-lup** [comment]
@Mystic999 did you try to use another cli ? Did it solve your issue ?

**Comment by Mystic999** [comment]
> @ Mystic999 ты пробовал использовать другой кли? Это решило вашу проблему?

Yes, this issue only applies to Git Bash. Other terminals work fine. Putty is fine. But can't it be fixed ? Don't forget that we are on Github, and Git Bash is a Git product.

**Comment by iulianpascalau** [comment]
Will close this issue here and move the conversation on elrond-go repo https://github.com/ElrondNetwork/elrond-go/issues/877
