### ISSUE TITLE
Fail Due to Github Rate Limiting

### ISSUE THREAD

**Issue by joesixpack** [ElrondNetwork/elrond-go-scripts-v2#36]
The way the script is currently designed, there seems to be no way to force a manual install or upgrade when it silently (!!!) fails to clone and/or download modules from Github once it blocks you due to the rate limiting.  I had to add my Github username and password to the curl command under git_clone in functions.cfg to finally get it work, so I recommend adding optional support for that as the rate limit is 83x higher.

**Comment by valentin-lup** [comment]
I am adding this as we speak ! 
I am putting a variable inside the variables.cfg and if added it will use the OAUTH token to pull tags from GITHUB !
Very well spotted ! Thanks :)

**Comment by smartins** [comment]
Lets use a separate location for variables.cfg so that we can easily pull new changes from github without having to move files out.

**Comment by valentin-lup** [comment]
Fixed this with latest version 😁
