### ISSUE TITLE
Weird Autoupgrade Behavior to .55

### ISSUE THREAD

**Issue by joesixpack** [ElrondNetwork/elrond-go-scripts-v2#38]
The nodes upgraded to .55 without a hitch, but then I received mail from crontab later on showing:

"^[[0;32mCloning into ^[[0;36melrond-go^[[0;32m with tag ^[[0;36mtags/v1.0.55^[[0;32m...^[[0m

^[[0;32mCloning into ^[[0;36melrond-config^[[0;32m with tag ^[[0;36mtags/BoN-ph2-w3-p11^[[0;32m...^[[0m

^[[0;32mDone ! Moving to next step...^[[0m

^[[0;32mBuilding your node from tag ^[[0;36mtags/v1.0.55^[[0;32m...^[[0m

^[[0;32mDownloading go modules...^[[0m

^[[0;32mCompiling binary...^[[0m

^[[0;32mCompiling the termui binary...^[[0m

^[[0;32mCompiling the logviewer binary ...^[[0m

^[[0;32mCopying libwasmer to your LIB folder...^[[0m

^[[0;32mCopying termui & logviewer binaries to elrond-utils...^[[0m

cp: cannot create regular file '/home/ubuntu/elrond-utils/': No such file or directory"

Checking variables.cfg several times showed no changes from my edits.  Ran ./script upgrade and it finished completely.  However, then I received another mail indicating the autoupdater status was failing due to the /home/ubuntu path.  Checking variables.cfg again and then it was then back to default!

My hypothesis is that either variables.cfg was in use while whatever was running and protecting the edits before the new copy was to overwrite it when permissable, and/or the crontab environmental variables are different than what is set in the shell (they are separate) since autoupgrader and github_pull are being called directly.

**Comment by joesixpack** [comment]
Pretty clear the scripts upgraded about 7 hours before the node did.  If variables.cfg was locked in use, you would still be seeing your variable.cfg edits even though the default was waiting to overwrite it which may have happened during the upgrade process to fail on the termui cp.

**Comment by valentin-lup** [comment]
@joesixpack that could be it
