### ISSUE TITLE
will the format of "*This release should start with a new DB*" be consistent to use in non-official scripts?

### ISSUE THREAD

**Issue by AGx10k** [ElrondNetwork/elrond-go-scripts-v2#39]
subj @valentin-lup ?

i am not using official scripts but hardly modified copy of old Alwin scripts. will the format of notification for db removal be consistent?

**Comment by valentin-lup** [comment]
Hey @AGx10k !
At least for now this is the case. the *This release should start with a new DB* will be present in the release notes if the DB needs to be erased.
