### ISSUE TITLE
.Profile is Growing Infinitely

### ISSUE THREAD

**Issue by joesixpack** [ElrondNetwork/elrond-go-scripts-v2#40]
export GOPATH="$HOME/go"
export GOBIN="$GOPATH/bin"
#export GOROOT="/usr/lib/go"
export PATH="$HOME/.local/bin:$GOPATH/bin:$HOME/.cargo/bin:$PATH"
export PATH=/home/j/.local/share/solana/install/active_release/bin:/home/j/.local/bin:/home/j/go/bin:/home/j/.cargo/bin:/home/j/.local/share/solana/install/active_release/bin:/home/j/.local/bin:/home/j/go/bin:/home/j/.cargo/bin:/home/j/.local/share/solana/install/active_release/bin:/home/j/.local/bin:/home/j/go/bin:/home/j/.cargo/bin:/home/j/.local/share/solana/install/active_release/bin:/home/j/.local/bin:/home/j/go/bin:/home/j/.cargo/bin:/home/j/.local/share/solana/install/active_release/bin:/home/j/.local/bin:/home/j/go/bin:/home/j/.cargo/bin:/home/j/.nvm/versions/node/v10.16.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/go/bin:/home/j/go/bin:/usr/local/go/bin:/home/j/go/bin
export GOPATH=/home/j/go
export PATH=/home/j/.local/share/solana/install/active_release/bin:/home/j/.local/bin:/home/j/go/bin:/home/j/.cargo/bin:/home/j/.local/share/solana/install/active_release/bin:/home/j/.local/bin:/home/j/go/bin:/home/j/.cargo/bin:/home/j/.local/share/solana/install/active_release/bin:/home/j/.local/bin:/home/j/go/bin:/home/j/.cargo/bin:/home/j/.local/share/solana/install/active_release/bin:/home/j/.local/bin:/home/j/go/bin:/home/j/.cargo/bin:/home/j/.local/share/solana/install/active_release/bin:/home/j/.local/bin:/home/j/go/bin:/home/j/.cargo/bin:/home/j/.nvm/versions/node/v10.16.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/go/bin:/home/j/go/bin:/usr/local/go/bin:/home/j/go/bin
export GOPATH=/home/j/go

etc.

**Comment by valentin-lup** [comment]
@joesixpack I think this has been solved for a while now... can you please confirm ?

**Comment by joesixpack** [comment]
Yes, it seems fixed.
