### ISSUE TITLE
The Script run 4 nodes instead of 6 (my input)

### ISSUE THREAD

**Issue by tramyargabam** [ElrondNetwork/elrond-go-scripts-v2#43]
I want to run 6 nodes in my VPS but the script stopped me to do that, instead of 6 nodes (my input in the question on "how much node you want to run) the script run 4 nodes.
I do that several time but no hope,  
Hope you solve this issue. I can provide screenshot if needed

VPS SPECS:
8 cores CPU , 30 GB of RAM,  800GB SSD storage and unlimited bandwidth

**Comment by smartins** [comment]
8 cores is the minimum configuration for 4 nodes (2 cores per node), so perhaps the script is checking the number of cores available?

**Comment by tramyargabam** [comment]
> 8 cores is the minimum configuration for 4 nodes (2 cores per node), so perhaps the script is checking the number of cores available?

Don't know, but I try other script by Alwin and its working fine in my specs
And also the documentation of the script don't include that info (chucking cores available)

**Comment by smartins** [comment]
@tramyargabam  Alwin script isn't to be used anymore since you lose the automated update functionality. Also running nodes under spec or just at the edge of the minimum specs will make them under-perform and have an impact on the number of blocks you can process (and ERD rewards accordingly)

**Comment by smartins** [comment]
Also, you need 200 GB per node, so the minimum specs to run 6 nodes in a server (which is a terrible idea since if the server goes down so does all your nodes) is 12 cores, 24+ GB ram and 1.2TB of disk space.

**Comment by tramyargabam** [comment]
> @tramyargabam Alwin script isn't to be used anymore since you lose the automated update functionality. Also running nodes under spec or just at the edge of the minimum specs will make them under-perform and have an impact on the number of blocks you can process (and ERD rewards accordingly)

Yup I know that the Alwin Script is not use anymore but I try that script to see if my system has an problem to run 6 nodes, with that try the result is looking good that my system can run 6 nodes.

**Comment by tramyargabam** [comment]
> Also, you need 200 GB per node, so the minimum specs to run 6 nodes in a server (which is a terrible idea since if the server goes down so does all your nodes) is 12 cores, 24+ GB ram and 1.2TB of disk space.

If the Script can detect that, its better to show some error message that I can run only a four nodes with that specs

**Comment by valentin-lup** [comment]
@tramyargabam the script isn't checking your specs before creating the nodes. I will test this issue and see if I can replicate the error.
@smartins you are very right... not a good idea to run so many nodes on a single machine... nonetheless it should work...

**Comment by dendenqy** [comment]
> @tramyargabam the script isn't checking your specs before creating the nodes. I will test this issue and see if I can replicate the error.
> @smartins you are very right... not a good idea to run so many nodes on a single machine... nonetheless it should work...

thanks for that , I just trying how the script adopt in that kind of stuff.

**Comment by tramyargabam** [comment]
> @tramyargabam the script isn't checking your specs before creating the nodes. I will test this issue and see if I can replicate the error.
> @smartins you are very right... not a good idea to run so many nodes on a single machine... nonetheless it should work...

thanks for that , I just trying how the script adopt in that kind of stuff and I fund that bug
