### ISSUE TITLE
config/variables.cfg seems to be reset

### ISSUE THREAD

**Issue by ahakla** [ElrondNetwork/elrond-go-scripts-v2#45]
Somehow the config/variables.cfg seems to be reset to the default values for some people.

Strangely, the script.sh version is still 1.2.1.

Is it possible that the backup of variables.cfg to variables_backup.cfg fails it the backup file already exists? Or anything like that?

**Comment by valentin-lup** [comment]
It shouldn't be a problem... the "-f" for the cp command should now make double sure ! Thanks !
