### ISSUE TITLE
Script failed to run auto-update from v.1.0.61 to v.1.0.62

### ISSUE THREAD

**Issue by tramyargabam** [ElrondNetwork/elrond-go-scripts-v2#48]
Since the latest patch (v.1.0.62) the auto-update fail 3x to pull the new patch so I triggered to do it manually.
Crontab is working maybe on the upgrade code.
![Screenshot_20191214_102130](https://user-images.githubusercontent.com/52567038/70842278-8bd46b00-1e5c-11ea-94ba-530cc18c3b64.png)

**Comment by tramyargabam** [comment]
Another screenshot in my VPS 
![Screenshot_20191214_114756](https://user-images.githubusercontent.com/52567038/70843098-a2cc8a80-1e67-11ea-8136-6f22648e5b82.png)

**Comment by valentin-lup** [comment]
Hi !
Can you tell me on what version of the scripts you are ?

**Comment by dendenqy** [comment]
latest, but is working now I reinstall my vps OS and install all of the stuff that needed.

**Comment by tramyargabam** [comment]
latest version, but its working perfectly now after the latest patch of the Elrond go
