### ISSUE TITLE
1.0.83 Weird Behavior

### ISSUE THREAD

**Issue by joesixpack** [ElrondNetwork/elrond-go-scripts-v2#53]
While on 1.0.83, the cron job reported:

Date: Thu, 23 Jan 2020 05:04:42 +0100 (CET)

/home/j/elrond-go-scripts-v2/auto-updater.sh: line 20: /home/ubuntu/autoupdate.status: No such file or directory

**Comment by valentin-lup** [comment]
I think probably a miss-configured variables file ? It used "ubuntu" (default in variables) instead of "j" the correct user.

**Comment by joesixpack** [comment]
Very likely.  In some cases the config file with the variables was overwritten.  Haven't seen that in a long time except once.
