### ISSUE TITLE
Don't `apt upgrade`, grub upgrade prompt will hang script. 

### ISSUE THREAD

**Issue by harsh-98** [ElrondNetwork/elrond-go-scripts-v2#66]
Apt upgrade tried to upgrade grub , prompt resulted in hanging. Apart from this, it is not required to upgrade at [line 12#functions.cfg](https://github.com/ElrondNetwork/elrond-go-scripts-v2/blob/master/config/functions.cfg#L12).

https://www.digitalocean.com/community/questions/ubuntu-new-boot-grub-menu-lst-after-apt-get-upgrade.

**Comment by valentin-lup** [comment]
This has been fixed. Made update & upgrade fully unattended.
