### ISSUE TITLE
auto-updater.sh abort when first node is not running and a 2nd is running.

### ISSUE THREAD

**Issue by gitpasqualito** [ElrondNetwork/elrond-go-scripts-v2#69]
hello team,

following line just test first node listening on 8080 port:
`CURRENT=$(curl -s http://localhost:8080/node/status | jq -r .details.erd_app_version)`

if first node is not running (in my config a backup node ready to start if another fail), but if a 2nd node listening on 8081 port and running then the following test will abort autoupdate needed for 2nd running node :
```
if [ -z "$CURRENT" ]; then
                      echo "Could not get latest current version !!! Node(s) not running ! Aborting..."
```

perhaps do a test code based on ~/..numberofnodes and test 8080, 8081, 8082,....

regards
--
telegram: @poussette

**Comment by frankf1957** [comment]
@valentin-lup 

Can be fixed by getting the version number from the node binary, like this:

$HOME/elrond-nodes/node-0/node --version | awk -F '[ \/-]' '{print $6}'
v1.0.134

**Comment by viastake** [comment]
See PR #74 , thanks @frankf1957 !

**Comment by LucianMincu** [comment]
Thanks @viastake @frankf1957 PR #74 merged.
