### ISSUE TITLE
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

### ISSUE THREAD

**Issue by frankf1957** [ElrondNetwork/elrond-go-scripts-v2#70]
I did a cleanup and install on one of my observers and saw the following message during the install, three times:

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

This has been reported by others in the Validators TC.

I believe the fix for that would be to switch from using 'apt' to using 'apt-get'

**Comment by frankf1957** [comment]
elrond@ubuntu-s-2vcpu-2gb-nyc3-01:~/elrond-go-scripts-v2$ bash script.sh install
How many nodes do you want to run ? : 1

Updating system & installing some dependencies...

All packages are up to date.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.


WARNING: apt does not have a stable CLI interface. Use with caution in scripts.


WARNING: apt does not have a stable CLI interface. Use with caution in scripts.


Limiting journalctl node units logs size...

SystemMaxUse=900M
SystemMaxFileSize=100M
Task completed.


GO is already installed: go version go1.14.4 linux/amd64...skipping install


Cloning into elrond-go with tag tags/v1.0.130...

Cloning into elrond-config with tag tags/v1.0.130...

Done ! Moving to next step...


Building your node from tag tags/v1.0.130...

Downloading go modules...

Compiling binary...

Done !
Building arwen binary...
go: found github.com/ElrondNetwork/arwen-wasm-vm/cmd/arwen in github.com/ElrondNetwork/arwen-wasm-vm v0.3.19
Done !
Compiling the termui binary...

Compiling the logviewer binary ...

Copying libwasmer to your LIB folder...


Building key generator...

Copying binary & configs for node-0 to /home/elrond/elrond-nodes/node-0...

Copying termui & logviewer binaries to elrond-utils...


Time to choose a node name...

Choose a custom name (default elrond-validator-0): 

Found PEMs on host for node-0. Copying them to node-0 config folder...

Archive:  /home/elrond/VALIDATOR_KEYS/node-0.zip
  inflating: /home/elrond/elrond-nodes/node-0/config/validatorKey.pem  

Installing systemd unit for node-0...


--------------------------------------------------------------------------------
---> This next section asks if you want to install the AUTOPUDATER
--------------------------------------------------------------------------------

Do you want to install the auto-update function (Default No) ? (Yy/Nn)Y

Adding auto-update to crontab !
elrond@ubuntu-s-2vcpu-2gb-nyc3-01:~/elrond-go-scripts-v2$

**Comment by frankf1957** [comment]
That seems to have fixed it.

I ran script.sh stop and script.sh cleanup, then edited config/functions.cfg and replaced the string apt as follows
```
:s/ apt / apt-get /g
```
Then I ran script.sh install, and the WARNING message is no longer displayed.

**Comment by frankf1957** [comment]
```
elrond@ubuntu-s-2vcpu-2gb-nyc3-01:~/elrond-go-scripts-v2$ bash ./script.sh install
How many nodes do you want to run ? : 1

Updating system & installing some dependencies...


Limiting journalctl node units logs size...

SystemMaxUse=900M
SystemMaxFileSize=100M
Task completed.


GO is already installed: go version go1.14.4 linux/amd64...skipping install


Cloning into elrond-go with tag tags/v1.0.130...

Cloning into elrond-config with tag tags/v1.0.130...

Done ! Moving to next step...


Building your node from tag tags/v1.0.130...

Downloading go modules...

Compiling binary...

Done !
Building arwen binary...
go: found github.com/ElrondNetwork/arwen-wasm-vm/cmd/arwen in github.com/ElrondNetwork/arwen-wasm-vm v0.3.19
Done !
Compiling the termui binary...

Compiling the logviewer binary ...

Copying libwasmer to your LIB folder...


Building key generator...

Copying binary & configs for node-0 to /home/elrond/elrond-nodes/node-0...

Copying termui & logviewer binaries to elrond-utils...


Time to choose a node name...

Choose a custom name (default elrond-validator-0): 

Found PEMs on host for node-0. Copying them to node-0 config folder...

Archive:  /home/elrond/VALIDATOR_KEYS/node-0.zip
  inflating: /home/elrond/elrond-nodes/node-0/config/validatorKey.pem  

Installing systemd unit for node-0...


--------------------------------------------------------------------------------
---> This next section asks if you want to install the AUTOPUDATER
--------------------------------------------------------------------------------

Do you want to install the auto-update function (Default No) ? (Yy/Nn)Y

Adding auto-update to crontab !
elrond@ubuntu-s-2vcpu-2gb-nyc3-01:~/elrond-go-scripts-v2$

**Comment by valentin-lup** [comment]
What could happen, in theory, is that apt could change tomorrow to calling them "distributions" instead of "packages" (because it "does not have a stable CLI interface yet") and this would completely break that function in the scripts.
But, realistically, the interface has been stable for years and probably isn't changing any time soon... 
Still I'll revert the scripts to the older apt-get.
